name: doctoron
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.3.2+3
  provider: ^4.3.3
  rxdart: ^0.24.1
  dart_extensions: ^1.0.1
  stacked: ^1.7.6
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.4+1
  firebase_crashlytics: ^0.2.3
  firebase_messaging: ^7.0.3
  firebase_analytics: ^6.2.0
  google_sign_in: ^4.4.1
  google_fonts: ^1.1.0
  json_annotation: ^2.0.0
  cupertino_icons: ^0.1.3
  smooth_page_indicator: ^0.2.0
  flutter_signin_button: ^1.0.0
  flutter_awesome_buttons: ^0.1.0
  package_info: ^0.4.1
  webview_flutter: ^2.0.2
  shared_preferences: ^0.5.12
  flutter_svg: ^0.18.0
  badges: ^1.1.1
  uni_links: ^0.4.0
  animations: ^1.1.2
  show_up_animation: ^1.0.2
  flutter_picker: ^1.1.5
  loading_indicator: ^1.2.0
  awesome_dialog: ^1.2.0
  url_launcher: ^6.0.2
  modal_bottom_sheet: ^2.0.0
  age: ^0.0.1
  device_info: ^0.4.2+9
  apple_sign_in: ^0.1.0
  grouped_list: ^3.7.1
  external_app_launcher: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^0.1.9
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
